timeout: 5
verbose: yes
serial: yes

wallpaper: boot():/boot/HorizonOS/HorizonOS-Logo-Limine.png
wallpaper_style: centered
backdrop: 0x000000

randomise_memory: no

interface_resolution: 1920x1080
interface_branding: HorizonOS
interface_branding_color: 4

/HorizonOS
    protocol: limine
    kernel_path: boot():/boot/HorizonOS/HorizonOS_Kernel
    resolution: 1920x1080x32
    kaslr: yes
    randomise_hhdm_base: yes

    module_path: boot():/boot/HorizonOS/HorizonOS.sym
    module_string: Symbol
    module_path: boot():/boot/HorizonOS/services/name_registry
    module_path: boot():/boot/HorizonOS/services/uacpi
    module_path: boot():/boot/HorizonOS/services/pci
    module_path: boot():/boot/HorizonOS/services/nvme
    module_path: boot():/boot/HorizonOS/services/storage_manager
    module_path: boot():/boot/HorizonOS/services/ext2
    module_path: boot():/boot/HorizonOS/services/vfs

    module_path: boot():/boot/HorizonOS/programs/hello_world