name: Build Riscv64

on:
  workflow_run:
    workflows: [ "Setup Deps" ]
    types:
      - completed

jobs:
  build-riscv64-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Restore Deps Folder
        id: cache-deps-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{github.workspace}}/deps/llvm
          key: ${{runner.os}}-horizonos-llvm

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install meson==1.9.1 ninja

      - name: Install xorriso
        run: sudo apt-get install xorriso

      - name: Setup Meson
        run: cd ${{github.workspace}} && meson setup --cross-file res/riscv64/horizon-cross.cfg -Dqemu_targets=false build

      - name: Build
        run: cd ${{github.workspace}} && meson compile HorizonOS_ISO

      - name: Upload ISO
        id: upload-iso
        uses: actions/upload-artifact@v5
        with:
          name: HorizonOS ISO - Release
          path: ${{github.workspace}}/iso/out/HorizonOS-riscv64.iso
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'

  build-riscv64-debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Restore Deps Folder
        id: cache-deps-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{github.workspace}}/deps/llvm
          key: ${{runner.os}}-horizonos-llvm

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install meson==1.9.1 ninja

      - name: Install xorriso
        run: sudo apt-get install xorriso

      - name: Setup Meson
        run: cd ${{github.workspace}} && meson setup --cross-file res/riscv64/horizon-cross.cfg -Ddebug_build=true -Dqemu_targets=false build

      - name: Build
        run: cd ${{github.workspace}} && meson compile HorizonOS_ISO -Ddebug_build=true

      - name: Upload ISO
        id: upload-iso
        uses: actions/upload-artifact@v5
        with:
          name: HorizonOS ISO - Debug
          path: ${{github.workspace}}/iso/out/HorizonOS-riscv64.iso
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'

      - name: Upload Kernel
        id: upload-kernel
        uses: actions/upload-artifact@v5
        with:
          name: HorizonOS Kernel - Debug
          path: ${{github.workspace}}/iso/riscv64/boot/HorizonOS/HorizonOS_Kernel
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'