name: Build X86_64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-x86_64-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Restore Toolchain
        id: cache-toolchain-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{github.workspace}}/toolchain
          key: ${{runner.os}}-horizonos-toolchain-x86_64

      - name: Restore Sysroot
        id: cache-sysroot-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{github.workspace}}/libs/sysroot
          key: ${{runner.os}}-horizonos-x86_64-sysroot

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install meson ninja

      - name: Install xorriso
        run: sudo apt-get install xorriso

      - name: Install RSync
        run: sudo apt-get install rsync

      - name: Setup Deps
        run: sh deps/setup_deps.sh trunk trunk trunk trunk for-5.0 horizon-tcmalloc horizon-abseil-cpp

      - name: Setup Meson
        run: cd ${{github.workspace}} && meson setup --cross-file res/x86_64/horizon-cross.cfg -Dqemu_targets=false build

      - name: Build
        run: cd ${{github.workspace}}/build && meson compile HorizonOS_ISO -j 10

      - name: Upload ISO
        id: upload-iso
        uses: actions/upload-artifact@v6
        with:
          name: HorizonOS ISO - Release
          path: ${{github.workspace}}/iso/out/HorizonOS-x86_64.iso
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'

  build-x86_64-debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Restore Toolchain
        id: cache-toolchain-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{github.workspace}}/toolchain
          key: ${{runner.os}}-horizonos-toolchain-x86_64

      - name: Restore Sysroot
        id: cache-sysroot-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{github.workspace}}/libs/sysroot
          key: ${{runner.os}}-horizonos-x86_64-sysroot

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install meson ninja

      - name: Install xorriso
        run: sudo apt-get install xorriso

      - name: Setup Deps
        run: sh deps/setup_deps.sh trunk trunk trunk trunk for-5.0 horizon-tcmalloc horizon-abseil-cpp

      - name: Setup Meson
        run: cd ${{github.workspace}} && meson setup --cross-file res/x86_64/horizon-cross.cfg -Ddebug_build=true -Dqemu_targets=false build

      - name: Build
        run: cd ${{github.workspace}}/build && meson compile HorizonOS_ISO

      - name: Upload ISO
        id: upload-iso
        uses: actions/upload-artifact@v5
        with:
          name: HorizonOS ISO - Debug
          path: ${{github.workspace}}/iso/out/HorizonOS-x86_64.iso
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'

      - name: Upload Kernel
        id: upload-kernel
        uses: actions/upload-artifact@v5
        with:
          name: HorizonOS Kernel - Debug
          path: ${{github.workspace}}/iso/x86_64/boot/HorizonOS/HorizonOS_Kernel
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'
