name: Build HorizonOS

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-llvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore Deps Folder
        id: cache-deps-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{github.workspace}}/deps/chdrs
            ${{github.workspace}}/deps/cxxhdrs
            ${{github.workspace}}/deps/flanterm
            ${{github.workspace}}/deps/limine
            ${{github.workspace}}/deps/llvm
            ${{github.workspace}}/deps/nanoprintf
            ${{github.workspace}}/deps/ovmf
            ${{github.workspace}}/deps/uacpi
          key: ${{runner.os}}-horizonos-deps

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/out/x86_64/release -S ${{github.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=Release -DHORIZON_ARCH=x86_64

      - name: Save Deps Folder
        id: cache-deps-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{github.workspace}}/deps/chdrs
            ${{github.workspace}}/deps/cxxhdrs
            ${{github.workspace}}/deps/flanterm
            ${{github.workspace}}/deps/limine
            ${{github.workspace}}/deps/llvm
            ${{github.workspace}}/deps/nanoprintf
            ${{github.workspace}}/deps/ovmf
            ${{github.workspace}}/deps/uacpi
          key: ${{steps.cache-deps-restore.outputs.cache-primary-key}}

  build-x86_64-release:
    runs-on: ubuntu-latest

    needs: build-llvm

    steps:
      - uses: actions/checkout@v4

      - name: Restore Deps Folder
        id: cache-deps-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{github.workspace}}/deps/chdrs
            ${{github.workspace}}/deps/cxxhdrs
            ${{github.workspace}}/deps/flanterm
            ${{github.workspace}}/deps/limine
            ${{github.workspace}}/deps/llvm
            ${{github.workspace}}/deps/nanoprintf
            ${{github.workspace}}/deps/ovmf
            ${{github.workspace}}/deps/uacpi
          key: ${{runner.os}}-horizonos-deps

      - name: Install lld
        run: sudo apt-get install lld

      - name: Install xorriso
        run: sudo apt-get install xorriso

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/out/x86_64/release -S ${{github.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=Release -DHORIZON_ARCH=x86_64

      - name: Update Dependencies
        run: cmake --build ${{github.workspace}}/out/x86_64/release --target Update-Main-Deps --config Release

      - name: Build
        run: cmake --build ${{github.workspace}}/out/x86_64/release --target HorizonOS-ISO --config Release

      - name: Upload ISO
        id: upload-iso
        uses: actions/upload-artifact@v4
        with:
          name: HorizonOS x86_64 ISO - Release
          path: ${{github.workspace}}/iso/out/HorizonOS-x86_64.iso
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'

      - name: Save Deps Folder
        id: cache-deps-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{github.workspace}}/deps/chdrs
            ${{github.workspace}}/deps/cxxhdrs
            ${{github.workspace}}/deps/flanterm
            ${{github.workspace}}/deps/limine
            ${{github.workspace}}/deps/llvm
            ${{github.workspace}}/deps/nanoprintf
            ${{github.workspace}}/deps/ovmf
            ${{github.workspace}}/deps/uacpi
          key: ${{steps.cache-deps-restore.outputs.cache-primary-key}}

  build-x86_64-debug:
    runs-on: ubuntu-latest

    needs: build-llvm

    steps:
      - uses: actions/checkout@v4

      - name: Restore Deps Folder
        id: cache-deps-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{github.workspace}}/deps/chdrs
            ${{github.workspace}}/deps/cxxhdrs
            ${{github.workspace}}/deps/flanterm
            ${{github.workspace}}/deps/limine
            ${{github.workspace}}/deps/llvm
            ${{github.workspace}}/deps/nanoprintf
            ${{github.workspace}}/deps/ovmf
            ${{github.workspace}}/deps/uacpi
          key: ${{runner.os}}-horizonos-deps

      - name: Install lld
        run: sudo apt-get install lld

      - name: Install xorriso
        run: sudo apt-get install xorriso

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/out/x86_64/debug -S ${{github.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=Debug -DHORIZON_ARCH=x86_64

      - name: Update Dependencies
        run: cmake --build ${{github.workspace}}/out/x86_64/debug --target Update-Main-Deps --config Debug

      - name: Build
        run: cmake --build ${{github.workspace}}/out/x86_64/debug --target HorizonOS-ISO --config Debug

      - name: Upload ISO
        id: upload-iso
        uses: actions/upload-artifact@v4
        with:
          name: HorizonOS x86_64 ISO - Debug
          path: ${{github.workspace}}/iso/out/HorizonOS-x86_64.iso
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'

      - name: Upload Kernel
        id: upload-kernel
        uses: actions/upload-artifact@v4
        with:
          name: HorizonOS x86_64 Kernel - Debug
          path: ${{github.workspace}}/iso/x86_64/boot/HorizonOS/HorizonOS_Kernel
          if-no-files-found: 'warn'
          retention-days: 14
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'

      - name: Save Deps Folder
        id: cache-deps-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{github.workspace}}/deps/chdrs
            ${{github.workspace}}/deps/cxxhdrs
            ${{github.workspace}}/deps/flanterm
            ${{github.workspace}}/deps/limine
            ${{github.workspace}}/deps/llvm
            ${{github.workspace}}/deps/nanoprintf
            ${{github.workspace}}/deps/ovmf
            ${{github.workspace}}/deps/uacpi
          key: ${{steps.cache-deps-restore.outputs.cache-primary-key}}

#  build-aarch64-release:
#    runs-on: ubuntu-latest

#    needs: build-llvm

#    steps:
#      - uses: actions/checkout@v4

#      - name: Restore Deps Folder
#        id: cache-deps-restore
#        uses: actions/cache/restore@v4
#        with:
#          path: |
#            ${{github.workspace}}/deps/chdrs
#            ${{github.workspace}}/deps/cxxhdrs
#            ${{github.workspace}}/deps/flanterm
#            ${{github.workspace}}/deps/limine
#            ${{github.workspace}}/deps/llvm
#            ${{github.workspace}}/deps/nanoprintf
#            ${{github.workspace}}/deps/ovmf
#            ${{github.workspace}}/deps/uacpi
#          key: ${{runner.os}}-horizonos-deps

#      - name: Install lld
#        run: sudo apt-get install lld

#      - name: Install xorriso
#        run: sudo apt-get install xorriso

#      - name: Configure CMake
#        run: cmake -B ${{github.workspace}}/out/aarch64/release -S ${{github.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=Release -DHORIZON_ARCH=aarch64

#      - name: Update Dependencies
#        run: cmake --build ${{github.workspace}}/out/aarch64/release --target Update-Main-Deps --config Release

#      - name: Build
#        run: cmake --build ${{github.workspace}}/out/aarch64/release --target HorizonOS-ISO --config Release

#      - name: Upload ISO
#        id: upload-iso
#        uses: actions/upload-artifact@v4
#        with:
#          name: HorizonOS AArch64 ISO - Release
#          path: ${{github.workspace}}/iso/out/HorizonOS-aarch64.iso
#          if-no-files-found: 'warn'
#          retention-days: 14
#          compression-level: '9'
#          overwrite: 'false'
#          include-hidden-files: 'false'

#      - name: Save Deps Folder
#        id: cache-deps-save
#        uses: actions/cache/save@v4
#        with:
#          path: |
#            ${{github.workspace}}/deps/chdrs
#            ${{github.workspace}}/deps/cxxhdrs
#            ${{github.workspace}}/deps/flanterm
#            ${{github.workspace}}/deps/limine
#            ${{github.workspace}}/deps/llvm
#            ${{github.workspace}}/deps/nanoprintf
#            ${{github.workspace}}/deps/ovmf
#            ${{github.workspace}}/deps/uacpi
#          key: ${{steps.cache-deps-restore.outputs.cache-primary-key}}

#  build-aarch64-debug:
#    runs-on: ubuntu-latest

#    needs: build-llvm

#    steps:
#      - uses: actions/checkout@v4

#      - name: Restore Deps Folder
#        id: cache-deps-restore
#        uses: actions/cache/restore@v4
#        with:
#          path: |
#            ${{github.workspace}}/deps/chdrs
#            ${{github.workspace}}/deps/cxxhdrs
#            ${{github.workspace}}/deps/flanterm
#            ${{github.workspace}}/deps/limine
#            ${{github.workspace}}/deps/llvm
#            ${{github.workspace}}/deps/nanoprintf
#            ${{github.workspace}}/deps/ovmf
#            ${{github.workspace}}/deps/uacpi
#          key: ${{runner.os}}-horizonos-deps

#      - name: Install lld
#        run: sudo apt-get install lld

#      - name: Install xorriso
#        run: sudo apt-get install xorriso

#      - name: Configure CMake
#        run: cmake -B ${{github.workspace}}/out/aarch64/debug -S ${{github.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=Debug -DHORIZON_ARCH=aarch64

#      - name: Update Dependencies
#        run: cmake --build ${{github.workspace}}/out/aarch64/debug --target Update-Main-Deps --config Debug

#      - name: Build
#        run: cmake --build ${{github.workspace}}/out/aarch64/debug --target HorizonOS-ISO --config Debug

#      - name: Upload ISO
#        id: upload-iso
#        uses: actions/upload-artifact@v4
#        with:
#          name: HorizonOS AArch64 ISO - Debug
#          path: ${{github.workspace}}/iso/out/HorizonOS-aarch64.iso
#          if-no-files-found: 'warn'
#          retention-days: 14
#          compression-level: '9'
#          overwrite: 'false'
#          include-hidden-files: 'false'

#      - name: Upload Kernel
#        id: upload-kernel
#        uses: actions/upload-artifact@v4
#        with:
#          name: HorizonOS AArch64 Kernel - Debug
#          path: ${{github.workspace}}/iso/aarch64/boot/HorizonOS/HorizonOS_Kernel
#          if-no-files-found: 'warn'
#          retention-days: 14
#          compression-level: '9'
#          overwrite: 'false'
#          include-hidden-files: 'false'

#      - name: Save Deps Folder
#        id: cache-deps-save
#        uses: actions/cache/save@v4
#        with:
#          path: |
#            ${{github.workspace}}/deps/chdrs
#            ${{github.workspace}}/deps/cxxhdrs
#            ${{github.workspace}}/deps/flanterm
#            ${{github.workspace}}/deps/limine
#            ${{github.workspace}}/deps/llvm
#            ${{github.workspace}}/deps/nanoprintf
#            ${{github.workspace}}/deps/ovmf
#            ${{github.workspace}}/deps/uacpi
#          key: ${{steps.cache-deps-restore.outputs.cache-primary-key}}

#  build-riscv64-release:
#    runs-on: ubuntu-latest

#    needs: build-llvm

#    steps:
#      - uses: actions/checkout@v4

#      - name: Restore Deps Folder
#        id: cache-deps-restore
#        uses: actions/cache/restore@v4
#        with:
#          path: |
#            ${{github.workspace}}/deps/chdrs
#            ${{github.workspace}}/deps/cxxhdrs
#            ${{github.workspace}}/deps/flanterm
#            ${{github.workspace}}/deps/limine
#            ${{github.workspace}}/deps/llvm
#            ${{github.workspace}}/deps/nanoprintf
#            ${{github.workspace}}/deps/ovmf
#            ${{github.workspace}}/deps/uacpi
#          key: ${{runner.os}}-horizonos-deps

#      - name: Install lld
#        run: sudo apt-get install lld

#      - name: Install xorriso
#        run: sudo apt-get install xorriso

#      - name: Configure CMake
#        run: cmake -B ${{github.workspace}}/out/riscv64/release -S ${{github.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=Release -DHORIZON_ARCH=riscv64

#      - name: Update Dependencies
#        run: cmake --build ${{github.workspace}}/out/riscv64/release --target Update-Main-Deps --config Release

#      - name: Build
#        run: cmake --build ${{github.workspace}}/out/riscv64/release --target HorizonOS-ISO --config Release

#      - name: Upload ISO
#        id: upload-iso
#        uses: actions/upload-artifact@v4
#        with:
#          name: HorizonOS Riscv64 ISO - Release
#          path: ${{github.workspace}}/iso/out/HorizonOS-riscv64.iso
#          if-no-files-found: 'warn'
#          retention-days: 14
#          compression-level: '9'
#          overwrite: 'false'
#          include-hidden-files: 'false'

#      - name: Save Deps Folder
#        id: cache-deps-save
#        uses: actions/cache/save@v4
#        with:
#          path: |
#            ${{github.workspace}}/deps/chdrs
#            ${{github.workspace}}/deps/cxxhdrs
#            ${{github.workspace}}/deps/flanterm
#            ${{github.workspace}}/deps/limine
#            ${{github.workspace}}/deps/llvm
#            ${{github.workspace}}/deps/nanoprintf
#            ${{github.workspace}}/deps/ovmf
#            ${{github.workspace}}/deps/uacpi
#          key: ${{steps.cache-deps-restore.outputs.cache-primary-key}}

#  build-riscv64-debug:
#    runs-on: ubuntu-latest

#    needs: build-llvm

#    steps:
#      - uses: actions/checkout@v4

#      - name: Restore Deps Folder
#        id: cache-deps-restore
#        uses: actions/cache/restore@v4
#        with:
#          path: |
#            ${{github.workspace}}/deps/chdrs
#            ${{github.workspace}}/deps/cxxhdrs
#            ${{github.workspace}}/deps/flanterm
#            ${{github.workspace}}/deps/limine
#            ${{github.workspace}}/deps/llvm
#            ${{github.workspace}}/deps/nanoprintf
#            ${{github.workspace}}/deps/ovmf
#            ${{github.workspace}}/deps/uacpi
#          key: ${{runner.os}}-horizonos-deps

#      - name: Install lld
#        run: sudo apt-get install lld

#      - name: Install xorriso
#        run: sudo apt-get install xorriso

#      - name: Configure CMake
#        run: cmake -B ${{github.workspace}}/out/riscv64/debug -S ${{github.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=Debug -DHORIZON_ARCH=riscv64

#      - name: Update Dependencies
#        run: cmake --build ${{github.workspace}}/out/riscv64/debug --target Update-Main-Deps --config Debug

#      - name: Build
#        run: cmake --build ${{github.workspace}}/out/riscv64/debug --target HorizonOS-ISO --config Debug

#      - name: Upload ISO
#        id: upload-iso
#        uses: actions/upload-artifact@v4
#        with:
#          name: HorizonOS Riscv64 ISO - Debug
#          path: ${{github.workspace}}/iso/out/HorizonOS-riscv64.iso
#          if-no-files-found: 'warn'
#          retention-days: 14
#          compression-level: '9'
#          overwrite: 'false'
#          include-hidden-files: 'false'

#      - name: Upload Kernel
#        id: upload-kernel
#        uses: actions/upload-artifact@v4
#        with:
#          name: HorizonOS Riscv64 Kernel - Debug
#          path: ${{github.workspace}}/iso/riscv64/boot/HorizonOS/HorizonOS_Kernel
#          if-no-files-found: 'warn'
#          retention-days: 14
#          compression-level: '9'
#          overwrite: 'false'
#          include-hidden-files: 'false'

#      - name: Save Deps Folder
#        id: cache-deps-save
#        uses: actions/cache/save@v4
#        with:
#          path: |
#            ${{github.workspace}}/deps/chdrs
#            ${{github.workspace}}/deps/cxxhdrs
#            ${{github.workspace}}/deps/flanterm
#            ${{github.workspace}}/deps/limine
#            ${{github.workspace}}/deps/llvm
#            ${{github.workspace}}/deps/nanoprintf
#            ${{github.workspace}}/deps/ovmf
#            ${{github.workspace}}/deps/uacpi
#          key: ${{steps.cache-deps-restore.outputs.cache-primary-key}}