name: Setup LLVM

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-llvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - uses: hendrikmuhs/ccache-action@v1.2

      - name: Restore Deps Folder
        id: cache-deps-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{github.workspace}}/deps/llvm/build
          key: ${{runner.os}}-horizonos-llvm

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install meson==1.9.1 ninja

      - name: Install xorriso
        run: sudo apt-get install xorriso

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Install RSync
        run: sudo apt-get install rsync

      - name: Setup Meson
        run: cd ${{github.workspace}} && meson setup -Dbuild_llvm=true -Dqemu_targets=false build

      - name: Upload LLVM
        id: upload-llvm
        uses: actions/upload-artifact@v5
        with:
          name: HorizonOS LLVM Build
          path: ${{github.workspace}}/deps/llvm/build
          if-no-files-found: 'warn'
          retention-days: 1
          compression-level: '9'
          overwrite: 'false'
          include-hidden-files: 'false'

      - name: Save Deps Folder
        id: cache-deps-save
        uses: actions/cache/save@v4
        with:
          path: ${{github.workspace}}/deps/llvm/build
          key: ${{steps.cache-deps-restore.outputs.cache-primary-key}}
